-- DIN UPPGIFT: skriv tabellerna här.
--
-- Datan som ska finnas:
--   transaktion: id, konto-id, belopp, tidpunkt
--   konto:       id, saldo
--
-- Frågor att ta ställning till (jag frågar efteråt):
--   1. Behövs en kontotabell alls, eller räcker transaktionstabellen?
--   2. Vilken typ för ett uuid i SQLite? Varför?
--   3. Belopp är heltal i specen. Varför heltal och inte decimaltal för pengar?
--   4. Hur lagrar du tidpunkten så att sortering fungerar?
--   5. Behövs index? På vad?
--
-- Skriv CREATE TABLE-satserna nedanför den här raden.
